/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(libs.jackson.databind)
}

application {
    // Define the main class for the application.
    mainClass = "pl.informatysta.aid4.s01e01.App"
}
